replicaCount: 2

image:
  repository: xlen911/couchbase-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: couchbase-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# ✅ Agregar sección de autoscaling
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

couchbase:
  connectionString: "couchbase://couchbase-cluster.couchbase-dev.svc.cluster.local"
  username: "Administrator"
  password: "TempP@ssw0rd2026!"
  bucket: "customers"
  scope: "sales"

config:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"