apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchbase-app.fullname" . }}

type: Opaque

stringData:
  COUCHBASE_USERNAME: {{ .Values.couchbase.username | quote }}
  COUCHBASE_PASSWORD: {{ .Values.couchbase.password | quote }}